--[[
    profile generation javascript script; botnames is an array that must be defined
var st = "";
for (var i = 0; i < 122; i++ ) {
    var x = botnames[i];
    st = st + "{name = "+x+", accuracy = "+Math.round(10+Math.random()*10)/20+", personality = "+Math.round(Math.random()*3)+"},\n";
}
console.log(st);

---------------------------

Personalities:
    { --[[ 0, nbghserd
        hide=true,
        groups=false,
        mean=true
    },
    { --[[ 1, mean teamer
        hide=false,
        groups=true,
        mean=true
    },
    { --[[ 2, semi nbghserd
        hide=false,
        groups=false,
        mean=false
    },
    { --[[ 3, team player
        hide=false,
        groups=true,
        mean=false
    }

]]
bot_profiles = {
    {name = "뚱이", accuracy = 1, personality = 1},
    {name = "무기", accuracy = 0.85, personality = 2},
    {name = "아니", accuracy = 0.75, personality = 1},
    {name = "님", accuracy = 0.8, personality = 1},
    {name = "고구마", accuracy = 0.95, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "Cyka", accuracy = 0.7, personality = 1},
    {name = "존윅", accuracy = 0.95, personality = 1},
    {name = "생존자", accuracy = 1, personality = 1},
    {name = "트레이터", accuracy = 0.65, personality = 1},
    {name = "loser", accuracy = 0.8, personality = 1},
    {name = "누군가", accuracy = 0.55, personality = 2},
    {name = "삐뽀", accuracy = 0.8, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "탐정", accuracy = 0.8, personality = 2},
    {name = "별", accuracy = 0.6, personality = 1},
    {name = "ㄹㅇㅋㅋ", accuracy = 0.85, personality = 3},
    {name = "내 친구", accuracy = 0.5, personality = 3},
    {name = "아킬레스", accuracy = 0.75, personality = 3},
    {name = "ㅁㄴㅇㄹ", accuracy = 0.9, personality = 1},
    {name = "호비", accuracy = 0.6, personality = 3},
    {name = "샌드위치", accuracy = 0.7, personality = 3},
    {name = "샌즈위치", accuracy = 0.65, personality = 1},
    {name = "응애", accuracy = 0.85, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "질럿", accuracy = 0.95, personality = 1},
    {name = "봇아니에요", accuracy = 0.6, personality = 2},
    {name = "소시지", accuracy = 0.95, personality = 3},
    {name = "테러리스트", accuracy = 0.85, personality = 1},
    {name = "싸닉", accuracy = 0.55, personality = 3},
    {name = "봇이에요", accuracy = 0.6, personality = 2},
    {name = "않이", accuracy = 0.6, personality = 1},
    {name = "신난다", accuracy = 0.9, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "샌즈TV", accuracy = 0.85, personality = 1},
    {name = "그림자", accuracy = 0.95, personality = 1},
    {name = "구독좋아요", accuracy = 0.7, personality = 3},
    {name = "안아줘요", accuracy = 0.95, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "아이", accuracy = 0.55, personality = 3},
    {name = "Cana", accuracy = 0.9, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "엄", accuracy = 0.85, personality = 1},
    {name = "69", accuracy = 0.9, personality = 1},
    {name = "Bot", accuracy = 0.7, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "ㅏㅏㅏㅏ", accuracy = 0.65, personality = 1},
    {name = "니코니코니", accuracy = 0.75, personality = 2},
    {name = "미쿠", accuracy = 0.55, personality = 2},
    {name = "쓰레기맨", accuracy = 0.95, personality = 2},
    {name = "고릴라", accuracy = 0.75, personality = 2},
    {name = "상어", accuracy = 0.95, personality = 1},
    {name = "타노스", accuracy = 0.55, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "좀비", accuracy = 0.95, personality = 1},
    {name = " ", accuracy = 0.55, personality = 2},
    {name = "저는 강도에요", accuracy = 0.95, personality = 2},
    {name = "그", accuracy = 0.9, personality = 1},
    {name = "안녕하세요", accuracy = 0.85, personality = 2},
    {name = "고양이", accuracy = 0.75, personality = 3},
    {name = "자신", accuracy = 1, personality = 1},
    {name = "주세요", accuracy = 0.9, personality = 2},
    {name = "코코코", accuracy = 0.55, personality = 2},
    {name = "블루", accuracy = 0.6, personality = 3},
    {name = "고양이 강도", accuracy = 0.65, personality = 1},
    {name = "스폰", accuracy = 0.6, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "나", accuracy = 0.7, personality = 2},
    {name = "이트", accuracy = 0.8, personality = 1},
    {name = "구아바", accuracy = 0.55, personality = 2},
    {name = "ㅔ", accuracy = 0.75, personality = 2},
    {name = ".", accuracy = 0.9, personality = 2},
    {name = "Bot01", accuracy = 0.8, personality = 3},
    {name = "고든", accuracy = 0.65, personality = 3},
    {name = "프리맨", accuracy = 1, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "윌슨", accuracy = 0.9, personality = 2},
    {name = "윌로우", accuracy = 0.7, personality = 1},
    {name = "어머", accuracy = 0.55, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "겐지", accuracy = 0.55, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "쓰레기", accuracy = 0.95, personality = 3},
    {name = "디퓨저", accuracy = 0.95, personality = 1},
    {name = "시체", accuracy = 0.8, personality = 2},
    {name = "AC", accuracy = 0.7, personality = 3},
    {name = "제임스", accuracy = 0.65, personality = 1},
    {name = "본드", accuracy = 0.7, personality = 2},
    {name = "크리티", accuracy = 0.8, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "스파이", accuracy = 0.75, personality = 1},
    {name = "ㅋ", accuracy = 0.9, personality = 2},
    {name = "마이크", accuracy = 0.9, personality = 3},
    {name = "최면술사", accuracy = 0.7, personality = 3},
    {name = "이노센트", accuracy = 0.6, personality = 2},
    {name = "아니", accuracy = 0.8, personality = 1},
    {name = "트레이터", accuracy = 0.65, personality = 1},
    {name = "자칼", accuracy = 0.8, personality = 2},
    {name = "님", accuracy = 0.85, personality = 2},
    {name = "몰?루", accuracy = 0.95, personality = 2},
    {name = "히트맨", accuracy = 0.7, personality = 2},
    {name = "언노운", accuracy = 0.7, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "서바이벌리스트", accuracy = 0.95, personality = 1},
    {name = "허접", accuracy = 0.9, personality = 2},
    {name = "캬루", accuracy = 0.7, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "ERROR 404", accuracy = 0.9, personality = 2},
    {name = "Сука Блядь", accuracy = 0.65, personality = 2},
    {name = "미셸", accuracy = 0.65, personality = 3},
    {name = "감자", accuracy = 0.7, personality = 2},
    {name = "존시나", accuracy = 0.95, personality = 1 --[[was a personality of 0 prior to edit]]},
    {name = "CuteDogXD", accuracy = 0.95, personality = 0},
    {name = "RIOT", accuracy = 0.85, personality = 0},
    {name = "사랑해요", accuracy = 0.55, personality = 2},
    {name = "아버", accuracy = 0.55, personality = 3},
    {name = "사이드킥", accuracy = 0.8, personality = 2},
    {name = "너", accuracy = 0.55, personality = 1},
    {name = "자신?", accuracy = 0.95, personality = 2},
    {name = "아버", accuracy = 0.5, personality = 1},
    {name = "제스터", accuracy = 0.85, personality = 1},
    {name = "광대", accuracy = 0.6, personality = 2},
    {name = "스니퍼", accuracy = 0.6, personality = 0},
    {name = "샌즈", accuracy = 0.65, personality = 0},
    {name = "Han Shot First", accuracy = 0.9, personality = 2},
    {name = "잼민이", accuracy = 0.95, personality = 1},
    {name = "Bot 01", accuracy = 0.85, personality = 2},
    {name = "BOT01", accuracy = 0.8, personality = 2},
    {name = "탐정", accuracy = 0.7, personality = 1},
    {name = "ㅇ", accuracy = 0.7, personality = 2},
    {name = "애옹", accuracy = 0.65, personality = 1},
    {name = "어쩔티비", accuracy = 0.55, personality = 1},
    {name = "불곰", accuracy = 0.55, personality = 2},
    {name = "잼민TV", accuracy = 0.5, personality = 1},
    {name = "메딕", accuracy = 1, personality = 3},
    {name = "아이고", accuracy = 0.75, personality = 2},
    {name = "지미", accuracy = 0.65, personality = 1}
}
